const express = require('express');
const bodyParser =require('body-parser');
const port = process.env.PORT || 3000;
var getProduct = require('./routes/getProducts');
var saveUserAddress = require('./routes/saveUserAddress');
var createUserOrders = require('./routes/createUserOrders');
var getUserAddress = require('./routes/getUserAddress');
var addUserAddress = require('./routes/addUserAddress');
var editUserAddress = require('./routes/editUserAddress');
var deleteUserAddress = require('./routes/deleteUserAddress');
var getUserOrders = require('./routes/getUserOrders');
var getUserOrderDetails = require('./routes/getUserOrderDetails');
var usersignup = require('./routes/usersignup');
var userlogin = require('./routes/userlogin');
var app = express();
app.use(bodyParser.json());
var bookshelf = app.get('bookshelf');
app.get('/getProducts',getProduct.getProducts);
app.post('/saveUserAddress',saveUserAddress.saveUserAddress);
app.post('/createUserOrders',createUserOrders.createUserOrders);
app.get('/getUserAddress',getUserAddress.getUserAddress);
app.post('/addUserAddress',addUserAddress.addUserAddress);
app.put('/editUserAddress',editUserAddress.editUserAddress);
app.delete('/deleteUserAddress',deleteUserAddress.deleteUserAddress);
app.get('/getUserOrders',getUserOrders.getUserOrders);
app.get('/getUserOrderDetails',getUserOrderDetails.getUserOrderDetails);
app.post('/usersignup',usersignup.usersignup);
app.post('/userlogin',userlogin.userlogin);
app.listen(port, function(){
  console.log(`started on port ${port}`);
});
